[package]
name = "pledge-example-2018"
version = "0.0.0"
authors = ["Andrew Aldridge <i80and@foxquill.com>", "Delan Azabani <delan@azabani.com>"]
edition = "2018"
publish = false

[dependencies.pledge]
path = ".."
