[workspace]

[package]
name = "pledge-variants"
version = "0.0.0"
authors = ["Heli Aldridge <heli@heli.pet>", "Delan Azabani <delan@azabani.com>"]
edition = "2018"
publish = false

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking"] }
scraper = "0.11.0"
