[package]
name = "pledge-example-2015"
version = "0.0.0"
authors = ["Heli Aldridge <heli@heli.pet>", "Delan Azabani <delan@azabani.com>"]
edition = "2015"
publish = false

[dependencies.pledge]
path = ".."
