[package]
name = "pledge-example-2015"
version = "0.0.0"
authors = ["Andrew Aldridge <i80and@foxquill.com>", "Delan Azabani <delan@azabani.com>"]
edition = "2015"
publish = false

[dependencies.pledge]
path = ".."
